# Generated by Django 6.0.1 on 2026-02-13 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('avatar', models.CharField(default='👤', max_length=10)),
                ('wpm', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('difficulty', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-wpm'],
            },
        ),
    ]
